Repository fit-us/server-supporting-system, pull requests merged in 2025-03, with the labels that each got.

#4 websocket 기반으로 메시지 송수신 로직 구성
  chat/cmd/main.go
  chat/config/database.go
  chat/config/env.go
  chat/go.mod
  chat/go.sum
  chat/internal/repository/message_repository.go
  chat/internal/service/message_service.go
Labels: 새로운 기능, 우선 순위 : 상

#8 cbt bot 이전 대화 기록 기억 기능 추가 ( ConversationBufferMemory 기반)
  cbt-bot/cbt_bot_llm.py
  cbt-bot/main.py
  cbt-bot/utils/json_serializer.py
  cbt-bot/utils/markdown_utils.py
Labels: enhancement

#9 cbt bot llm 모델을 gRPC 를 통해서 접근할 수 있도록 적용
  cbt-bot/Makefile
  cbt-bot/cbt_bot_llm.py
  cbt-bot/cbt_bot_model.py
  cbt-bot/cbt_bot_proto/__init__.py
  cbt-bot/cbt_bot_proto/cbt_bot.proto
  cbt-bot/cbt_bot_proto/cbt_bot_llm.proto
  cbt-bot/cbt_bot_proto/cbt_bot_llm_pb2.py
  cbt-bot/cbt_bot_proto/cbt_bot_llm_pb2_grpc.py
  cbt-bot/cbt_bot_proto/cbt_bot_pb2.py
  cbt-bot/cbt_bot_proto/cbt_bot_pb2_grpc.py
  cbt-bot/example/grpc_cbt_client.py
  cbt-bot/example/grpc_client.py
  cbt-bot/example/grpc_server.py
  cbt-bot/main.py
  cbt-bot/proto/cbt_bot.proto
  cbt-bot/utils/__init__.py
  cbt-bot/utils/json_serializer.py
Labels: enhancement, 우선 순위 : 상

#10 사용자별로 각자 기억력을 부여하여 처리하도록 Conversation Memory 분리
  cbt-bot/cbt_bot_llm.py
  cbt-bot/cbt_bot_proto/cbt_bot_llm.proto
  cbt-bot/cbt_bot_proto/cbt_bot_llm_pb2.py
  cbt-bot/main.py
Labels: 새로운 기능, 우선 순위 : 상

#18 메시지 누락 문제 처리 및 LLM 프롬프트 최적화
  cbt-bot/assets/system-analysis-prompt.md
  cbt-bot/assets/system-cbt-prompt.md
  cbt-bot/assets/system-summary-prompt.md
  cbt-bot/cbt_bot_llm.py
  cbt-bot/config.py
  cbt-bot/main.py
  cbt-bot/utils/json_serializer.py
Labels: enhancement, 새로운 기능, 우선 순위 : 상
